name: promptFCL
dependencies:
  - pip:
      - fairscale==0.4.13
      - matplotlib==3.6.3
      - numpy==1.24.2
      - pyyaml==6.0
      - scipy==1.10.0
      - tensorboard==2.12.0
      - timm==0.6.12
      - torch==1.13.1
      - torchvision==0.14.1
      - tqdm==4.64.1
      - wandb==0.13.10
      - werkzeug==2.2.2
